# Generated by Django 3.1.3 on 2021-01-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.IntegerField(default=0)),
                ('Order_Data', models.DateTimeField(verbose_name='Create Date')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=200)),
                ('Catalog_Id', models.IntegerField(default=0)),
                ('Client_Id', models.IntegerField(default=0)),
                ('Order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zamowienia.orderid')),
            ],
        ),
    ]
