# Generated by Django 3.1.3 on 2021-01-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Client_Id',
            new_name='Item_Cost',
        ),
        migrations.AddField(
            model_name='order',
            name='Client_Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
